name: Generate Windows Release

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: vednig/pyinstaller-action-windows@main
        with:
          path: .
          spec: main.spec

      - name: Copy dist files to correct directory
        run: |
          ls -l;
          sudo ls -l ./dist
          sudo ls -l ./dist/windows/
          sudo cp ./dist/windows/main.exe ./TournamentStreamHelper.exe
          sudo rm -rf dist;

      - uses: actions/upload-artifact@v2
        with:
          name: TSH_Windows
          path: .
