name: Build Locale files

on:
  push:
    branches:
      - main
      - feature/ui-translations
      - locale/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - run: pip install -r dependencies/requirements.txt pyinstaller==4.10
      - run: |
          python3 src/i18n/gen_translation_files.py
          python3 src/i18n/gen_translation_binaries.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TSH.exe
          git commit -m "Update locale files" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
